<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ModelBinders\**" />
    <EmbeddedResource Remove="ModelBinders\**" />
    <None Remove="ModelBinders\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire" Version="1.8.23" />
    <PackageReference Include="Hangfire.Dashboard.BasicAuthorization" Version="1.0.2" />
    <PackageReference Include="Hangfire.Extensions.Configuration" Version="1.0.0" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.23" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Serilog" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\SharedEvents\SharedEvents.csproj" />
    <ProjectReference Include="..\System.Domain\System.Domain.csproj" />
  </ItemGroup>

</Project>
