// <auto-generated />
using System;
using System.Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace System.Infrastructure.Migrations.Drive
{
    [DbContext(typeof(DriveContext))]
    partial class DriveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("System.Domain.Entities.Blob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("InsDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Container");
                });

            modelBuilder.Entity("System.Domain.Entities.Metadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("InsDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("JsFormat")
                        .HasColumnType("bit");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("UpdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BlobId");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("System.Domain.Entities.Metadata", b =>
                {
                    b.HasOne("System.Domain.Entities.Blob", "Blob")
                        .WithMany()
                        .HasForeignKey("BlobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blob");
                });
#pragma warning restore 612, 618
        }
    }
}
