// <auto-generated />
using System;
using System.Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Files.Infrastructure.Migrations
{
    [DbContext(typeof(FilesContext))]
    [Migration("20260306224923__init")]
    partial class _init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Files.Domain.Entities.AdditionalData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("GameGenre")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("InsDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Semester")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdditionalData");
                });

            modelBuilder.Entity("Files.Domain.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdditionalDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Content")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<Guid?>("Image")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("InsDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Locaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalDataId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Files.Domain.Entities.SourceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Imported")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("InsDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Files.Domain.Entities.File", b =>
                {
                    b.HasOne("Files.Domain.Entities.AdditionalData", "AdditionalData")
                        .WithMany()
                        .HasForeignKey("AdditionalDataId");

                    b.Navigation("AdditionalData");
                });

            modelBuilder.Entity("Files.Domain.Entities.SourceLink", b =>
                {
                    b.HasOne("Files.Domain.Entities.File", null)
                        .WithMany("Sources")
                        .HasForeignKey("FileId");
                });

            modelBuilder.Entity("Files.Domain.Entities.File", b =>
                {
                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
