<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PreserveCompilationContext>true</PreserveCompilationContext>
	</PropertyGroup>

	<PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Middleware\**" />
	  <EmbeddedResource Remove="Middleware\**" />
	  <None Remove="Middleware\**" />
	</ItemGroup>

  <ItemGroup>
    <Folder Include="EntityConfiguration\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
    <PackageReference Include="QuestPDF" Version="2026.2.3" />
    <PackageReference Include="Razor.Templating.Core" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RPG.Domain\RPG.Domain.csproj" />
  </ItemGroup>

</Project>
