// <auto-generated />
using System;
using Automation.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Automation.Infrastructure.Migrations
{
    [DbContext(typeof(AutomationContext))]
    partial class AutomationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Automation.Domain.Entities.Automat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("InsDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastRun")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Automats");
                });

            modelBuilder.Entity("Automation.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AutomatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("InsDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("UpdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AutomatId");

                    b.ToTable("AutomatTasks");
                });

            modelBuilder.Entity("Automation.Domain.Entities.Trigger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AutomatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cron")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("InsBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("InsDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AutomatId");

                    b.ToTable("Triggers");
                });

            modelBuilder.Entity("Automation.Domain.Entities.Task", b =>
                {
                    b.HasOne("Automation.Domain.Entities.Automat", null)
                        .WithMany("Tasks")
                        .HasForeignKey("AutomatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Automation.Domain.Entities.Trigger", b =>
                {
                    b.HasOne("Automation.Domain.Entities.Automat", null)
                        .WithMany("Triggers")
                        .HasForeignKey("AutomatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Automation.Domain.Entities.Automat", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("Triggers");
                });
#pragma warning restore 612, 618
        }
    }
}
