<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PreserveCompilationContext>true</PreserveCompilationContext>
	</PropertyGroup>
	
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Base\Base.csproj" />
  </ItemGroup>

</Project>
